import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function generateHealthReport(user, history, stats) {
  const doc = new jsPDF()
  const pageW = doc.internal.pageSize.getWidth()
  const now = new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' })

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFillColor(30, 41, 59)
  doc.rect(0, 0, pageW, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('MediPredict', 14, 18)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('AI Health Report', 14, 26)
  doc.text(`Generated: ${now}`, pageW - 14, 26, { align: 'right' })

  // ── Patient Info ──────────────────────────────────────────────────────────
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('Patient Information', 14, 54)
  doc.setDrawColor(99, 102, 241)
  doc.setLineWidth(0.5)
  doc.line(14, 57, pageW - 14, 57)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(60, 60, 80)
  const info = [
    ['Name', user?.full_name || 'N/A'],
    ['Email', user?.email || 'N/A'],
    ['Gender', user?.gender || 'N/A'],
    ['Age', user?.age ? `${user.age} years` : 'N/A'],
    ['Blood Group', user?.blood_group || 'N/A'],
  ]
  info.forEach(([label, val], i) => {
    doc.setFont('helvetica', 'bold')
    doc.text(`${label}:`, 14, 66 + i * 8)
    doc.setFont('helvetica', 'normal')
    doc.text(val, 60, 66 + i * 8)
  })

  // ── Stats Summary ─────────────────────────────────────────────────────────
  let y = 112
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text('Prediction Summary', 14, y)
  doc.setDrawColor(99, 102, 241)
  doc.line(14, y + 3, pageW - 14, y + 3)
  y += 12

  if (stats) {
    const boxes = [
      ['Total', stats.total_predictions || 0, [99, 102, 241]],
      ['Disease', stats.by_type?.disease || 0, [16, 185, 129]],
      ['Diabetes', stats.by_type?.diabetes || 0, [245, 158, 11]],
      ['Heart', stats.by_type?.heart || 0, [239, 68, 68]],
    ]
    const bw = (pageW - 28 - 9) / 4
    boxes.forEach(([label, val, color], i) => {
      const x = 14 + i * (bw + 3)
      doc.setFillColor(...color)
      doc.roundedRect(x, y, bw, 22, 3, 3, 'F')
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(16)
      doc.setFont('helvetica', 'bold')
      doc.text(String(val), x + bw/2, y + 11, { align:'center' })
      doc.setFontSize(7)
      doc.setFont('helvetica', 'normal')
      doc.text(label, x + bw/2, y + 18, { align:'center' })
    })
    y += 32
  }

  // ── Prediction History Table ───────────────────────────────────────────────
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 41, 59)
  doc.text('Prediction History', 14, y)
  doc.setDrawColor(99, 102, 241)
  doc.line(14, y + 3, pageW - 14, y + 3)
  y += 8

  if (history?.length > 0) {
    const rows = history.map((r, i) => {
      const date = new Date(r.created_at).toLocaleDateString('en-IN')
      let result = ''
      if (r.prediction_type === 'disease') {
        const top = r.result?.predictions?.[0]
        result = top ? `${top.disease} (${top.confidence}%)` : 'N/A'
      } else {
        result = `${r.result?.risk_score}% — ${r.result?.risk_level} Risk`
      }
      return [i + 1, date, r.prediction_type?.toUpperCase(), result]
    })

    autoTable(doc, {
      startY: y,
      head: [['#', 'Date', 'Type', 'Result']],
      body: rows,
      theme: 'striped',
      headStyles: { fillColor: [99, 102, 241], textColor: 255, fontStyle: 'bold', fontSize: 9 },
      bodyStyles: { fontSize: 9, textColor: [40, 40, 60] },
      alternateRowStyles: { fillColor: [245, 247, 255] },
      columnStyles: { 0: { cellWidth: 12 }, 1: { cellWidth: 28 }, 2: { cellWidth: 28 } },
      margin: { left: 14, right: 14 },
    })
  } else {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120, 120, 140)
    doc.text('No prediction history found.', 14, y + 8)
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  const pages = doc.internal.getNumberOfPages()
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 170)
    doc.setFont('helvetica', 'normal')
    doc.text('This report is generated by MediPredict AI and is for informational purposes only. Consult a doctor for medical advice.', pageW / 2, doc.internal.pageSize.getHeight() - 8, { align: 'center' })
    doc.text(`Page ${p} of ${pages}`, pageW - 14, doc.internal.pageSize.getHeight() - 8, { align: 'right' })
  }

  const fileName = `MediPredict_Report_${user?.full_name?.replace(/\s/g,'_') || 'User'}_${Date.now()}.pdf`

  // Detect Capacitor (Android app) vs browser
  const isCapacitor = typeof window !== 'undefined' && window.Capacitor !== undefined

  if (isCapacitor) {
    // Android WebView — open PDF as data URI in new window
    const dataUri = doc.output('datauristring')
    const newWin = window.open('', '_blank')
    if (newWin) {
      newWin.document.write(
        `<html><head><title>${fileName}</title></head>` +
        `<body style="margin:0;padding:0;background:#000;">` +
        `<iframe src="${dataUri}" width="100%" height="100%" style="border:none;position:fixed;top:0;left:0;width:100%;height:100%;"></iframe>` +
        `</body></html>`
      )
      newWin.document.close()
    } else {
      // Fallback: share via data URI directly
      const link = document.createElement('a')
      link.href = dataUri
      link.download = fileName
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    }
  } else {
    // Browser — standard blob download (most reliable)
    try {
      const blob = doc.output('blob')
      const url  = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href     = url
      link.download = fileName
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      setTimeout(() => URL.revokeObjectURL(url), 3000)
    } catch {
      // Last fallback
      doc.save(fileName)
    }
  }
}
